version: '3.8'
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    networks:
      - lakelon_dev

networks:
  lakelon_dev:
    external: true
